name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  lockfile:
    runs-on: ubuntu-latest

    container:
      image: quay.io/fedora-ostree-desktops/buildroot:latest
      options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout base ostree config
        run: git clone https://pagure.io/workstation-ostree-config.git --branch f39 --single-branch --depth 1

      # Repo not loaded relatively to the imported file
      - name: Copy repo files
        run: cp -r workstation-ostree-config/*.repo .

      - name: Remove gnome-software
        run: sed -i '/gnome-software/d' workstation-ostree-config/gnome-desktop-pkgs.yaml

      - name: Login to GitHub Container Registry
        run: skopeo login -u ${{ github.repository_owner }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io

      - name: Build image
        run: rpm-ostree compose image  --initialize-mode=if-not-exists --format=registry silverblue.yaml ghcr.io/${{ github.repository }}/silverblue:latest
